/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    palettes: Palette;
    colors: Color;
    accessories: Accessory;
    products: Product;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    palettes: PalettesSelect<false> | PalettesSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    accessories: AccessoriesSelect<false> | AccessoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Color palettes grouped by layer purpose (exterior, interior, accessory).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palettes".
 */
export interface Palette {
  id: number;
  /**
   * Human-readable name shown in admin (e.g., "Exterior (default)").
   */
  name: string;
  /**
   * Stable identifier used in code & API (e.g., "exterior", "accUpholstery").
   */
  key: string;
  type: 'exterior' | 'interior' | 'accessory';
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual color swatches. Each belongs to a palette.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  palette: number | Palette;
  /**
   * SKU code used in image filenames (e.g., "WH", "GBN"). Must be unique within a palette.
   */
  code: string;
  /**
   * Display name (e.g., "White", "Burgundy").
   */
  name: string;
  /**
   * Hex color for swatch background (e.g., "#6b1d2a").
   */
  bgColor: string;
  /**
   * Optional. Hex color for swatch border. Defaults to bgColor.
   */
  borderColor?: string | null;
  /**
   * Optional. Used for textured swatches (e.g., interior PET fabric).
   */
  swatchImage?: (number | null) | Media;
  /**
   * Display order within the palette.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add-on items (benches, desks, sofas) that can be toggled on a booth.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessories".
 */
export interface Accessory {
  id: number;
  /**
   * Display name shown in the configurator (e.g., "Flex Bench").
   */
  label: string;
  /**
   * Stable identifier (e.g., "flex-bench").
   */
  code: string;
  /**
   * Which render layer this accessory occupies (e.g., "accBench").
   */
  layerKey: string;
  /**
   * SKU pattern, use {colour} as placeholder (e.g., "L3_AC_FB_{colour}").
   */
  skuTemplate: string;
  /**
   * Which color palette this accessory pulls from.
   */
  palette: number | Palette;
  /**
   * Pre-selected color SKU code (must exist in the palette).
   */
  defaultColorCode: string;
  /**
   * Optional. Color codes from the palette to hide for this accessory (e.g., ["GLB"]).
   */
  excludedColorCodes?:
    | {
        code: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * SAM booth variants. Each booth has its own image set on S3 and palette of options.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Full booth name (e.g., "Sam Single Booth").
   */
  title: string;
  /**
   * Short label for header tab (e.g., "Single").
   */
  label: string;
  /**
   * Internal key (e.g., "single", "medium", "large"). No spaces.
   */
  slug: string;
  /**
   * Short description shown below the title.
   */
  subtitle?: string | null;
  /**
   * Order in which booths appear in the header.
   */
  sortOrder?: number | null;
  status?: ('published' | 'draft') | null;
  /**
   * 2-letter prefix used in SKU codes (e.g., "SS", "SM", "SL").
   */
  skuPrefix: string;
  /**
   * S3 folder URL for this booth's images (e.g., "https://kolo-website.s3.../sam_single").
   */
  assetBaseUrl: string;
  /**
   * Panel code that means "no walls, all glass" (e.g., "GS_NA").
   */
  allGlassCode: string;
  /**
   * Which palette to use for exterior color options.
   */
  exteriorPalette: number | Palette;
  /**
   * Which palette to use for interior PET color options.
   */
  interiorPalette: number | Palette;
  /**
   * Accessories available on this booth (leave empty if none).
   */
  accessories?: (number | Accessory)[] | null;
  /**
   * Back panel options available on this booth.
   */
  panels?:
    | {
        /**
         * Panel SKU code (e.g., "GS_GS", "GS_WL").
         */
        code: string;
        /**
         * Display name (e.g., "2 Glasses").
         */
        label: string;
        icon: 'glass' | 'wall' | '2glass' | '2wall' | 'glass-wall' | 'wall-glass';
        id?: string | null;
      }[]
    | null;
  /**
   * Render layers, in z-index order (low = back, high = front).
   */
  layers?:
    | {
        /**
         * Layer identifier (e.g., "panel", "interior", "exterior", "door", "accBench").
         */
        key: string;
        /**
         * S3 subfolder name (e.g., "panel", "frame", "accessories").
         */
        folder: string;
        /**
         * Stack order: lower numbers render behind higher ones.
         */
        zIndex: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Disallowed combinations (e.g., "WL_WL" panel cannot use "BUR" interior).
   */
  panelRestrictions?:
    | {
        /**
         * Panel code that triggers the restriction.
         */
        panelCode: string;
        excludedInteriorCodes?:
          | {
              code: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'palettes';
        value: number | Palette;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'accessories';
        value: number | Accessory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "palettes_select".
 */
export interface PalettesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  palette?: T;
  code?: T;
  name?: T;
  bgColor?: T;
  borderColor?: T;
  swatchImage?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessories_select".
 */
export interface AccessoriesSelect<T extends boolean = true> {
  label?: T;
  code?: T;
  layerKey?: T;
  skuTemplate?: T;
  palette?: T;
  defaultColorCode?: T;
  excludedColorCodes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  slug?: T;
  subtitle?: T;
  sortOrder?: T;
  status?: T;
  skuPrefix?: T;
  assetBaseUrl?: T;
  allGlassCode?: T;
  exteriorPalette?: T;
  interiorPalette?: T;
  accessories?: T;
  panels?:
    | T
    | {
        code?: T;
        label?: T;
        icon?: T;
        id?: T;
      };
  layers?:
    | T
    | {
        key?: T;
        folder?: T;
        zIndex?: T;
        id?: T;
      };
  panelRestrictions?:
    | T
    | {
        panelCode?: T;
        excludedInteriorCodes?:
          | T
          | {
              code?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}